version: '3.8'

services:
  # --- Backend App ---
  backend:
    build: ./backend
    container_name: medicloud-backend
    restart: always
    environment:
      # PENTING: Pastikan ini baca variable dari file .env
      DATABASE_URL: ${DATABASE_URL}
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3000:3000"
    networks:
      - medicloud_network

  # --- Frontend App ---
  frontend:
    build: ./frontend
    container_name: medicloud-frontend
    restart: always
    ports:
      - "5173:80"
    networks:
      - medicloud_network

networks:
  medicloud_network:
    name: medicloud_network
    external: true
