version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: medicloud-db
    restart: always
    environment:
      POSTGRES_USER: medicloud
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: medicloud_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  medicloud-network:
    driver: bridge
