version: '3.8'

services:
  # --- Backend App ---
  backend:
    build: ./backend
    container_name: medicloud-backend
    restart: always
    environment:
      # PENTING: Pastikan ini baca variable dari file .env
      DATABASE_URL: ${DATABASE_URL}
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3000:3000"

  # --- Frontend App ---
  frontend:
    build: ./frontend
    container_name: medicloud-frontend
    restart: always
    ports:
      - "5173:80" # Mapping port frontend

  # --- LOAD BALANCER AGENT (Cloudflared) ---
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: medicloud-tunnel
    restart: always
    # Token ini akan kita taruh di file .env biar aman
    command: tunnel run --token ${TUNNEL_TOKEN}
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:15
    container_name: medicloud-db
    restart: always
    environment:
      POSTGRES_USER: medicloud
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: medicloud_db
    ports:
      - "5432:5432"